package com.mycompany.desafio1;


import com.google.maps.GeoApiContext;
import com.google.maps.GeocodingApi;
import java.util.HashSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

public class DesafioUIL extends javax.swing.JFrame {

    /**
     * Creates new form DesafioUIL
     */
    public DesafioUIL() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PPessoa = new javax.swing.JPanel();
        TxtNome = new javax.swing.JTextField();
        TxtEmail = new javax.swing.JTextField();
        PEndereco = new javax.swing.JPanel();
        TxtCep = new javax.swing.JTextField();
        TxtEstado = new javax.swing.JTextField();
        TxtCidade = new javax.swing.JTextField();
        TxtBairro = new javax.swing.JTextField();
        TxtRua = new javax.swing.JTextField();
        TxtNumero = new javax.swing.JTextField();
        TxtComplemento = new javax.swing.JTextField();
        BtnAtualizarE = new javax.swing.JButton();
        BtnDeletarE = new javax.swing.JButton();
        BtnAnteriorE = new javax.swing.JButton();
        BtnProximoE = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        BtnAdicionarE = new javax.swing.JButton();
        BtnLimpar1 = new javax.swing.JButton();
        TxtTipo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtFieldCodigo = new javax.swing.JTextField();
        Mapa = new javax.swing.JButton();
        BtnAdicionarP = new javax.swing.JButton();
        BtnAtualizarP = new javax.swing.JButton();
        BtnDeletarP = new javax.swing.JButton();
        BtnAnteriorP = new javax.swing.JButton();
        BtnProximoP = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BtnPesquisarP = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        TxtId = new javax.swing.JTextField();
        BtnLimparPessoa = new javax.swing.JButton();
        TxtTelefone = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PPessoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        PEndereco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TxtEstado.setEditable(false);
        TxtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEstadoActionPerformed(evt);
            }
        });

        TxtCidade.setEditable(false);

        TxtBairro.setEditable(false);

        TxtRua.setEditable(false);

        BtnAtualizarE.setText("Atualizar Endereço");
        BtnAtualizarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtualizarEActionPerformed(evt);
            }
        });

        BtnDeletarE.setText("Deletar Endereço");
        BtnDeletarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeletarEActionPerformed(evt);
            }
        });

        BtnAnteriorE.setText("Anterior");
        BtnAnteriorE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnteriorEActionPerformed(evt);
            }
        });

        BtnProximoE.setText("Proximo");
        BtnProximoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProximoEActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipo");

        jLabel6.setText("Cep");

        jLabel7.setText("Estado");

        jLabel8.setText("Cidade");

        jLabel9.setText("Bairro");

        jLabel10.setText("Rua");

        jLabel11.setText("Número");

        jLabel12.setText("Complemento");

        BtnAdicionarE.setText("Adicionar Endereço");
        BtnAdicionarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdicionarEActionPerformed(evt);
            }
        });

        BtnLimpar1.setText("Limpar");
        BtnLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpar1ActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar Endereço");
        jButton1.setName("BtnBuscar"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel14.setText("Código");

        Mapa.setLabel("Mapa");
        Mapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MapaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PEnderecoLayout = new javax.swing.GroupLayout(PEndereco);
        PEndereco.setLayout(PEnderecoLayout);
        PEnderecoLayout.setHorizontalGroup(
            PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnLimpar1)
                        .addGap(32, 32, 32))
                    .addGroup(PEnderecoLayout.createSequentialGroup()
                        .addGroup(PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PEnderecoLayout.createSequentialGroup()
                                .addGroup(PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PEnderecoLayout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(TxtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PEnderecoLayout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(TxtCidade))
                                    .addGroup(PEnderecoLayout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtNumero)))
                                .addGap(18, 18, 18)
                                .addGroup(PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PEnderecoLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnAdicionarE)
                    .addGroup(PEnderecoLayout.createSequentialGroup()
                        .addComponent(BtnAnteriorE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnProximoE))
                    .addComponent(BtnDeletarE, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(BtnAtualizarE, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mapa))
                .addGap(63, 63, 63))
        );
        PEnderecoLayout.setVerticalGroup(
            PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PEnderecoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel5)
                    .addComponent(TxtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAnteriorE)
                    .addComponent(BtnProximoE)
                    .addComponent(BtnLimpar1))
                .addGap(18, 18, 18)
                .addGroup(PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TxtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(TxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAdicionarE))
                .addGroup(PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PEnderecoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(TxtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(TxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(TxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TxtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(PEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(TxtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PEnderecoLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(BtnDeletarE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnAtualizarE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Mapa)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jButton1.getAccessibleContext().setAccessibleName("Consulta End");

        BtnAdicionarP.setText("Adicionar Pessoa");
        BtnAdicionarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdicionarPActionPerformed(evt);
            }
        });

        BtnAtualizarP.setText("Atualizar Pessoa");
        BtnAtualizarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtualizarPActionPerformed(evt);
            }
        });

        BtnDeletarP.setText("Deletar Pessoa");
        BtnDeletarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeletarPActionPerformed(evt);
            }
        });

        BtnAnteriorP.setText("Anterior");

        BtnProximoP.setText("Proximo");

        jLabel2.setText("Nome");

        jLabel3.setText("Telefone");

        jLabel4.setText("E-mail");

        BtnPesquisarP.setText("Consultar Pessoa");
        BtnPesquisarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesquisarPActionPerformed(evt);
            }
        });

        jLabel13.setText("ID");

        BtnLimparPessoa.setText("Limpar");

        jLabel15.setText("jLabel15");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout PPessoaLayout = new javax.swing.GroupLayout(PPessoa);
        PPessoa.setLayout(PPessoaLayout);
        PPessoaLayout.setHorizontalGroup(
            PPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PPessoaLayout.createSequentialGroup()
                .addGroup(PPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PPessoaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(PEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PPessoaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PPessoaLayout.createSequentialGroup()
                                .addGroup(PPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PPessoaLayout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(TxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PPessoaLayout.createSequentialGroup()
                                        .addGroup(PPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PPessoaLayout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(20, 20, 20))
                                            .addGroup(PPessoaLayout.createSequentialGroup()
                                                .addGroup(PPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(12, 12, 12)))
                                        .addGroup(PPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PPessoaLayout.createSequentialGroup()
                                                .addGap(13, 13, 13)
                                                .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(TxtTelefone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                                .addComponent(TxtEmail, javax.swing.GroupLayout.Alignment.TRAILING)))))
                                .addGap(18, 18, 18)
                                .addGroup(PPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnLimparPessoa)
                                    .addGroup(PPessoaLayout.createSequentialGroup()
                                        .addComponent(BtnAnteriorP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnProximoP)))
                                .addGap(42, 42, 42)
                                .addGroup(PPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PPessoaLayout.createSequentialGroup()
                                        .addComponent(BtnPesquisarP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnAdicionarP))
                                    .addGroup(PPessoaLayout.createSequentialGroup()
                                        .addComponent(BtnAtualizarP, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnDeletarP, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 97, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        PPessoaLayout.setVerticalGroup(
            PPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PPessoaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(PPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnLimparPessoa)
                    .addComponent(BtnPesquisarP)
                    .addComponent(BtnAdicionarP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAnteriorP)
                    .addComponent(BtnProximoP)
                    .addComponent(BtnAtualizarP)
                    .addComponent(BtnDeletarP)
                    .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnDeletarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeletarPActionPerformed
        //BOTÃO DELETA PESSOA
        pessoa.setId(TxtId.getText());
        ALDAL.delete(pessoa);
        if (Erro.getErro())
        JOptionPane.showMessageDialog(null,Erro.getMens());
        else
        JOptionPane.showMessageDialog(null,"Dados Deletados com sucesso!");
    }//GEN-LAST:event_BtnDeletarPActionPerformed

    
    private void BtnAtualizarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtualizarPActionPerformed
        //BOTÃO ATUALIZAR PESSOA
        pessoa.setId(TxtId.getText());
        Pessoa dados = new Pessoa();
        dados.setNome(TxtNome.getText());
        dados.setTelefone(TxtTelefone.getText());
        dados.setEmail(TxtEmail.getText());
        
        ALDAL.update(dados,pessoa);
        if (Erro.getErro())
            JOptionPane.showMessageDialog(null,Erro.getMens());
        else{
            JOptionPane.showMessageDialog(null,"Dados Atualizados com sucesso!");
        }
        
    }//GEN-LAST:event_BtnAtualizarPActionPerformed

    private void BtnAdicionarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdicionarPActionPerformed
        // BOTÃO ADICIONAR PESSOA
        // *SÓ PODE FAZER O INSERT COM ENDEREÇO

        pessoa.setId(TxtId.getText());
        pessoa.setNome(TxtNome.getText());
        pessoa.setTelefone(TxtTelefone.getText());
        pessoa.setEmail(TxtEmail.getText());
        ALDAL.set(pessoa);
        if (Erro.getErro())
            JOptionPane.showMessageDialog(null,Erro.getMens());
        else
            JOptionPane.showMessageDialog(null,"Dados Salvos com sucesso!");
    }//GEN-LAST:event_BtnAdicionarPActionPerformed

    private void BtnPesquisarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesquisarPActionPerformed
        //BOTÃO PESQUISA PESSOA
        //erro, RETORNAR QUE NÃO ENCONTROU NADA!
        
        pessoa.setId(TxtId.getText());
        pessoa.setNome(TxtNome.getText());
        pessoa.setTelefone(TxtTelefone.getText());
        pessoa.setEmail(TxtEmail.getText());
        
        
        
        ALDAL.get(pessoa);
        if (Erro.getErro())
            JOptionPane.showMessageDialog(null,Erro.getMens());
        else
        {
            TxtId.setText(pessoa.getId());
            TxtNome.setText(pessoa.getNome());
            TxtTelefone.setText(pessoa.getTelefone());
            TxtEmail.setText(pessoa.getEmail());
        };
        
    }//GEN-LAST:event_BtnPesquisarPActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            codigo = -1;
            String cep = TxtCep.getText(); // Obtém o CEP digitado no campo de texto
            Endereco endereco = new Endereco();
            endereco.setCep(cep);
            endereco.setLatLng();
            ImageIcon icon = new ImageIcon(endereco.getStaticImage());
            jLabel15.setIcon(icon);
            ALDAL.setCep(endereco.getCep());
            TxtEstado.setText(DadosJson.getuf());
            TxtCidade.setText(DadosJson.getlocalidade());
            TxtBairro.setText(DadosJson.getbairro());
            TxtRua.setText(DadosJson.getlogradouro());
            TxtComplemento.setText(DadosJson.getcomplemento());

        }catch(Exception e){
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnAdicionarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdicionarEActionPerformed
        //BOTÃO ADICIONAR ENDEREÇO

        endereco.setCodigo(txtFieldCodigo.getText());
        endereco.setId(TxtId.getText());
        endereco.setTipo(TxtTipo.getText());
        endereco.setCep(TxtCep.getText());
        endereco.setEstado(TxtBairro.getText());
        endereco.setCidade(TxtCidade.getText());
        endereco.setBairro(TxtBairro.getText());
        endereco.setRua(TxtRua.getText());
        endereco.setNumero(TxtNumero.getText());
        endereco.setComplemento(TxtComplemento.getText());
        ALDAL.set(endereco);
        if (Erro.getErro())
        JOptionPane.showMessageDialog(null,Erro.getMens());
        else
        JOptionPane.showMessageDialog(null,"Dados Salvos com sucesso!");
    }//GEN-LAST:event_BtnAdicionarEActionPerformed

    private void BtnDeletarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeletarEActionPerformed

        endereco.setCodigo(txtFieldCodigo.getText());
        endereco.setId(TxtId.getText());
        endereco.setTipo(TxtTipo.getText());
        endereco.setCep(TxtCep.getText());
        endereco.setEstado(TxtEstado.getText());
        endereco.setCidade(TxtCidade.getText());
        endereco.setBairro(TxtBairro.getText());
        endereco.setRua(TxtRua.getText());
        endereco.setNumero(TxtNumero.getText());
        endereco.setComplemento(TxtComplemento.getText());
        ALDAL.delete(endereco);
    }//GEN-LAST:event_BtnDeletarEActionPerformed

    private void BtnAtualizarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtualizarEActionPerformed
        endereco.setCodigo(txtFieldCodigo.getText());
        endereco.setId(TxtId.getText());
        endereco.setTipo(TxtTipo.getText());
        endereco.setCep(TxtCep.getText());
        endereco.setEstado(TxtBairro.getText());
        endereco.setCidade(TxtCidade.getText());
        endereco.setBairro(TxtBairro.getText());
        endereco.setRua(TxtRua.getText());
        endereco.setNumero(TxtNumero.getText());
        endereco.setComplemento(TxtComplemento.getText());
        Endereco e = new Endereco();
        e.setCodigo(txtFieldCodigo.getText());
        ALDAL.update(endereco, e);
        txtFieldCodigo.setText(endereco.getCodigo());
        TxtTipo.setText(endereco.getTipo());
        TxtCep.setText(endereco.getCep());
        TxtEstado.setText(endereco.getEstado());
        TxtCidade.setText(endereco.getCidade());
        TxtBairro.setText(endereco.getBairro());
        TxtRua.setText(endereco.getRua());
        TxtNumero.setText(endereco.getNumero());
        TxtComplemento.setText(endereco.getComplemento());

    }//GEN-LAST:event_BtnAtualizarEActionPerformed

    private void TxtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEstadoActionPerformed

    }//GEN-LAST:event_TxtEstadoActionPerformed

    private void BtnProximoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProximoEActionPerformed
        
        codigo++;
        endereco.setCodigo(Integer.toString(codigo));
        endereco.setId(TxtId.getText());
        endereco.setTipo(null);
        endereco.setCep(null);
        endereco.setEstado(null);
        endereco.setCidade(null);
        endereco.setBairro(null);
        endereco.setRua(null);
        endereco.setNumero(null);
        endereco.setComplemento(null);
        
        ALDAL.get(endereco);
        if(!Erro.getErro()){
            txtFieldCodigo.setText(endereco.getCodigo());
            TxtTipo.setText(endereco.getTipo());
            TxtCep.setText(endereco.getCep());
            TxtEstado.setText(endereco.getEstado());
            TxtCidade.setText(endereco.getCidade());
            TxtBairro.setText(endereco.getBairro());
            TxtRua.setText(endereco.getRua());
            TxtNumero.setText(endereco.getNumero());
            TxtComplemento.setText(endereco.getComplemento());
        }else {
             txtFieldCodigo.setText("");
            TxtTipo.setText("");
            TxtCep.setText("");
            TxtEstado.setText("");
            TxtCidade.setText("");
            TxtBairro.setText("");
            TxtRua.setText("");
            TxtNumero.setText("");
            TxtComplemento.setText("");
        }
    }//GEN-LAST:event_BtnProximoEActionPerformed

    private void BtnAnteriorEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnteriorEActionPerformed
        codigo--;
        endereco.setCodigo(Integer.toString(codigo));
        endereco.setId(TxtId.getText());
        endereco.setTipo(null);
        endereco.setCep(null);
        endereco.setEstado(null);
        endereco.setCidade(null);
        endereco.setBairro(null);
        endereco.setRua(null);
        endereco.setNumero(null);
        endereco.setComplemento(null);
        ALDAL.get(endereco);
        if(!Erro.getErro()){
            txtFieldCodigo.setText(endereco.getCodigo());
            TxtCep.setText(endereco.getCep());
            TxtEstado.setText(endereco.getEstado());
            TxtCidade.setText(endereco.getCidade());
            TxtBairro.setText(endereco.getBairro());
            TxtRua.setText(endereco.getRua());
            TxtNumero.setText(endereco.getNumero());
            TxtComplemento.setText(endereco.getComplemento());
        }else {
             txtFieldCodigo.setText("");
            TxtTipo.setText("");
            TxtCep.setText("");
            TxtEstado.setText("");
            TxtCidade.setText("");
            TxtBairro.setText("");
            TxtRua.setText("");
            TxtNumero.setText("");
            TxtComplemento.setText("");
        }
    }//GEN-LAST:event_BtnAnteriorEActionPerformed

    private void BtnLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpar1ActionPerformed
        // TODO add your handling code here:
           txtFieldCodigo.setText("");
            TxtTipo.setText("");
            TxtCep.setText("");
            TxtEstado.setText("");
            TxtCidade.setText("");
            TxtBairro.setText("");
            TxtRua.setText("");
            TxtNumero.setText("");
            TxtComplemento.setText("");
    }//GEN-LAST:event_BtnLimpar1ActionPerformed

    private void MapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MapaActionPerformed
        Endereco endereco = new Endereco();
        endereco.setCep(TxtCep.getText());
        endereco.setRua(TxtRua.getText());
        endereco.setLatLng();
        endereco.Browser();
    }//GEN-LAST:event_MapaActionPerformed
 
    private void Limpar(String obj){
        if(obj == "P"){
            TxtId.setText("");
            TxtNome.setText("");
            TxtTelefone.setText("");
            TxtEmail.setText("");
        }
     
    }
    
    private Pessoa pessoa = new Pessoa();
    private Endereco endereco = new Endereco();
    private static int codigo = 0;
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesafioUIL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesafioUIL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesafioUIL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesafioUIL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DesafioUIL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdicionarE;
    private javax.swing.JButton BtnAdicionarP;
    private javax.swing.JButton BtnAnteriorE;
    private javax.swing.JButton BtnAnteriorP;
    private javax.swing.JButton BtnAtualizarE;
    private javax.swing.JButton BtnAtualizarP;
    private javax.swing.JButton BtnDeletarE;
    private javax.swing.JButton BtnDeletarP;
    private javax.swing.JButton BtnLimpar1;
    private javax.swing.JButton BtnLimparPessoa;
    private javax.swing.JButton BtnPesquisarP;
    private javax.swing.JButton BtnProximoE;
    private javax.swing.JButton BtnProximoP;
    private javax.swing.JButton Mapa;
    private javax.swing.JPanel PEndereco;
    private javax.swing.JPanel PPessoa;
    private javax.swing.JTextField TxtBairro;
    private javax.swing.JTextField TxtCep;
    private javax.swing.JTextField TxtCidade;
    private javax.swing.JTextField TxtComplemento;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtEstado;
    private javax.swing.JTextField TxtId;
    private javax.swing.JTextField TxtNome;
    private javax.swing.JTextField TxtNumero;
    private javax.swing.JTextField TxtRua;
    private javax.swing.JTextField TxtTelefone;
    private javax.swing.JTextField TxtTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtFieldCodigo;
    // End of variables declaration//GEN-END:variables


}
